class TestFlextGrpcConfig:
    def test_create_valid_config_with_defaults(self) -> None: ...
    def test_create_valid_config_with_custom_values(self) -> None: ...
    def test_invalid_empty_host(self) -> None: ...
    def test_invalid_whitespace_host(self) -> None: ...
    def test_invalid_port_too_low(self) -> None: ...
    def test_invalid_port_too_high(self) -> None: ...
    def test_invalid_max_workers_zero(self) -> None: ...
    def test_invalid_max_workers_negative(self) -> None: ...
    def test_valid_boundary_values(self) -> None: ...
    def test_get_address_method(self) -> None: ...
    def test_host_strip_whitespace(self) -> None: ...
    def test_invalid_timeout_zero(self) -> None: ...
    def test_invalid_timeout_negative(self) -> None: ...
