EXPECTED_BULK_SIZE: int

class TestFlextGrpcChannel:
    def test_create_valid_channel(self) -> None: ...
    def test_invalid_empty_target(self) -> None: ...
    def test_invalid_channel_state(self) -> None: ...
    def test_channel_connection_lifecycle(self) -> None: ...
    def test_invalid_state_transitions(self) -> None: ...

class TestFlextGrpcServer:
    def test_create_valid_server(self) -> None: ...
    def test_invalid_server_configuration(self) -> None: ...
    def test_server_lifecycle(self) -> None: ...
    def test_add_service_to_server(self) -> None: ...

class TestFlextGrpcService:
    def test_create_valid_service(self) -> None: ...
    def test_invalid_service_configuration(self) -> None: ...
    def test_add_method(self) -> None: ...

class TestFlextGrpcClient:
    def test_create_valid_client(self) -> None: ...
    def test_client_without_channel(self) -> None: ...
    def test_connect_to_target(self) -> None: ...

class TestFlextGrpcStream:
    def test_create_valid_stream(self) -> None: ...
    def test_invalid_stream_configuration(self) -> None: ...
    def test_stream_type_detection(self) -> None: ...
