class TestAPIFunctions:
    def test_create_server(self) -> None: ...
    def test_create_client(self) -> None: ...
    def test_create_channel(self) -> None: ...
    def test_create_service(self) -> None: ...
    def test_create_stream(self) -> None: ...
    def test_create_stream_invalid_type(self) -> None: ...
    def test_create_config(self) -> None: ...
    def test_validate_address(self) -> None: ...
    def test_validate_address_exception_handling(self) -> None: ...
    def test_parse_address(self) -> None: ...
    def test_create_complete_setup(self) -> None: ...
    def test_factory_functions_create_valid_entities(self) -> None: ...
    def test_factory_functions_use_proper_ids(self) -> None: ...
    def test_factory_functions_use_proper_timestamps(self) -> None: ...
