class TestFlextGrpcPlatformSimple:
    def setup_method(self) -> None: ...
    def test_platform_service_property_fallback_paths(self) -> None: ...
    def test_platform_operations_error_paths(self) -> None: ...
