class TestGrpcTypes:
    def test_grpc_target_type(self) -> None: ...
    def test_validate_target_valid_cases(self) -> None: ...
    def test_validate_target_invalid_cases(self) -> None: ...
    def test_parse_target_valid_cases(self) -> None: ...
    def test_parse_target_invalid_cases(self) -> None: ...
    def test_edge_cases(self) -> None: ...
    def test_hostname_patterns(self) -> None: ...
