class TestEntityValidationGaps:
    def test_entity_type_property_coverage(self) -> None: ...
    def test_channel_valid_states_coverage(self) -> None: ...
    def test_server_valid_states_coverage(self) -> None: ...
    def test_client_channel_none_validation(self) -> None: ...
    def test_service_empty_methods_validation(self) -> None: ...
    def test_stream_all_types_coverage(self) -> None: ...
    def test_server_zero_workers_validation(self) -> None: ...
    def test_channel_empty_target_validation(self) -> None: ...
    def test_all_entity_types_coverage(self) -> None: ...
