class TestFlextGrpcError:
    def test_base_error_creation(self) -> None: ...
    def test_base_error_inheritance(self) -> None: ...

class TestFlextGrpcValidationError:
    def test_validation_error_with_field_name(self) -> None: ...
    def test_validation_error_without_field_name(self) -> None: ...
    def test_validation_error_default_field_name(self) -> None: ...
    def test_validation_error_inheritance(self) -> None: ...

class TestFlextGrpcConnectionError:
    def test_connection_error_creation(self) -> None: ...
    def test_connection_error_inheritance(self) -> None: ...

class TestFlextGrpcTimeoutError:
    def test_timeout_error_creation(self) -> None: ...
    def test_timeout_error_inheritance(self) -> None: ...

class TestFlextGrpcConfigurationError:
    def test_configuration_error_with_all_params(self) -> None: ...
    def test_configuration_error_with_minimal_params(self) -> None: ...
    def test_configuration_error_with_key_only(self) -> None: ...
    def test_configuration_error_inheritance(self) -> None: ...

class TestErrorIntegration:
    def test_all_errors_are_exceptions(self) -> None: ...
    def test_error_hierarchy_consistency(self) -> None: ...
    def test_error_with_complex_scenarios(self) -> None: ...
