class TestServicesValidationGaps:
    def test_service_execute_missing_arguments(self) -> None: ...
    def test_service_execute_non_string_operation(self) -> None: ...
    def test_service_execute_invalid_service_type(self) -> None: ...
    def test_service_execute_invalid_operation(self) -> None: ...
    def test_service_execute_wrong_entity_type(self) -> None: ...
    def test_service_execute_insufficient_arguments_variations(self) -> None: ...
    def test_client_service_missing_arguments(self) -> None: ...
    def test_stream_service_missing_arguments(self) -> None: ...
    def test_service_execution_edge_cases(self) -> None: ...
