#!/usr/bin/env python3
<<<<<<< HEAD
"""AI Hub governance hook projection: gemini beforeagent.

Copyright (c) 2026 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

# Copyright (c) 2025 FLEXT Team. All rights reserved.
=======
"""gemini-beforeagent hook - generated by `agentsctl sync`.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""
>>>>>>> dup-261007
from __future__ import annotations

import json
import sys

"""AI Hub governance hook projection: gemini beforeagent."""


payload = json.load(sys.stdin)
if not isinstance(payload, dict):
    msg = "hook input must be a JSON object"
    raise TypeError(msg)
response = json.loads(
<<<<<<< HEAD
    (
        '{"hookSpecificOutput":{"hookEventName":"BeforeAgent","additional'
        'Context":"<!-- AIHUB-GOVERNANCE-CAPSULE v1 sha256:5888ee9f8147f6'
        "3364a4f7cd6906e9d837f58cb8a8546844760c526ecb1a303b -->\\n# Gener"
        "ated session governance capsule\\n\\nThis projection is derived "
        "by `agentsctl sync`; edit canonical `AGENTS.md`, `rules/`, `skil"
        "ls/`, or `commands/`, never this output. The operator's newest "
        "request has precedence. Provider hooks are delivery mechanisms, "
        "not policy owners.\\n\\n## Rule `architecture/engineering-core`\\"
        "n\\n# Engineering core\\n\\nFor every implementation:\\n\\n1. Re"
        "search repository owners, dependencies, and canonical documentat"
        "ion.\\n2. Remove scope without a current requirement or consumer"
        " (YAGNI).\\n3. Elect one writable authority; every other copy is"
        " a generated projection\\n   (SSOT).\\n4. Apply SOLID only to a "
        "responsibility or dependency boundary under change.\\n5. Impleme"
        "nt through the owner and simplify without weakening behavior.\\n"
        "6. Remove duplication and god components; recheck YAGNI, SSOT, S"
        "OLID.\\n7. Exercise runtime behavior, run every applicable nativ"
        "e gate, and complete\\n   the approved landing cycle before chan"
        "ging phase.\\n\\nAt a cross-boundary failure, prove the producer"
        " contract and output. Fix its\\nowner when invalid or the receiv"
        "er when it conforms. Never alter a correct\\nadjacent owner for "
        "an invalid consumer; symptom workarounds are defects.\\n\\nHardc"
        "odes, normalized failure, failover, retry, fallback, compatibili"
        "ty,\\npartial execution, keyring, and unevidenced success are de"
        "fects. Typed owners\\nkeep defaults. The first exception escapes"
        " its CLI with traceback and cause.\\n\\nGit, runtime, build, and"
        " tests are baseline. Auxiliary tracking is a capability.\\nAuxil"
        "iary capabilities apply only when authorized and selected; insta"
        "llation\\nnever selects. Do not load, probe, or gate dormant cap"
        "abilities. Invalid\\nselected authorization, configuration, read"
        "iness, or result fails without\\nfallback. Require only non-deri"
        "vable values.\\n\\nAn external token validation without its toke"
        "n is not executed and is recorded\\nas `NOT EXECUTED`, never gre"
        "en; it does not block offline gates, landing, or\\npost-merge pr"
        "oof. Direct invocation selects it: the token becomes required an"
        "d\\nany failure escapes without skip, catch, fallback, or normal"
        "ization.\\n\\nCompose with `generalized ownership` (rule file),\\"
        "n`strict execution` (rule file),\\n`runtime evidence` (rule file"
        "),\\n`storage isolation` (rule file),\\n`security closure` (rule"
        " file).\\n\\n## Rule `coordination/operator-precedence`\\n\\n# N"
        "ewest operator instruction wins; adjust artifacts to it\\n\\nAut"
        "hority order: operator request > declared orchestration contract"
        " > canonical\\ntracker > ADRs > skills > docs, and newest supers"
        "edes oldest. On conflict,\\nadjust the lower or older artifact t"
        "o match; never override the operator to\\nsatisfy stale guidance"
        ".\\n\\nWhile orchestration and tracker runtimes are suspended, d"
        "o not invoke them.\\nCreate no substitute tracker or ledger, pre"
        "serve implementation evidence only\\nin separately authorized Gi"
        "t/PR/CI, and leave phase closure open.\\n\\nExact operator autho"
        "rization naming targets, disposition, recovery, and\\nvalidation"
        " survives interruption, divergence, and red gates; re-preflight "
        "and\\ncontinue. Ask only when the effect expands beyond it or tw"
        "o evidenced current\\nintentions conflict. State alone proves no"
        " intention, actor, or process.\\n\\n## Rule `ethics/professional"
        "-integrity`\\n\\n# Professional integrity is absolute\\n\\nNever"
        " lie, fabricate evidence, hide a blocker, bypass a gate, or patc"
        "h a symptom\\nonly to make a check pass. Fix the generalized roo"
        "t cause with full context and\\nreport exact command, working di"
        "rectory, exit code and decisive output.\\n\\n## Rule `runtime/st"
        "rict-execution`\\n\\n# Strict execution is universal and non-opt"
        "ional\\n\\nEvery project and projected agent applies all of thes"
        "e policies together:\\n\\n- `fail loud` (rule file);\\n- `no fal"
        "lback` (rule file);\\n- `preflight before effects` (rule file);\\"
        "n- `required environment` (rule file);\\n- `atomic effects` (rul"
        "e file);\\n- `causal subprocess propagation` (rule file);\\n- `n"
        "o keyring` (rule file);\\n- `zero residue` (rule file).\\n\\nThe"
        " policies are cumulative. A project rule may make them narrower "
        "or reject\\nmore inputs; it cannot relax, catch, normalize, skip"
        ", defer, or route around any\\nof them. Existing opposing behavi"
        "or is a blocking violation to exterminate at\\nits owner, never "
        "grandfathered compatibility.\\n\\nResolve gate applicability bef"
        "ore invocation. A dormant external-token gate is\\nnot executed;"
        " selecting or invoking it applies every policy above.\\n\\n## Ca"
        "pability indexes\\n\\nSkills: caveman, context-canary, fix-forwa"
        "rd-collaboration, governance-audit, operator-correction-learning"
        ", plan-focus-recovery, sprint-closure, strategic-compact, verifi"
        "cation-loop\\nCommands: add-language-rules, database-migration, "
        "feature-development, ghi-list, pr-list, ralph-loop, security-tri"
        'age, synthesize-governance\\n"}}'
    ),
=======
    '{"hookSpecificOutput":{"hookEventName":"BeforeAgent","additionalContext":"<!'
    '-- AIHUB-GOVERNANCE-CAPSULE v1 sha256:5888ee9f8147f63364a4f7cd6906e9d837f58c'
    'b8a8546844760c526ecb1a303b -->\\n# Generated session governance capsule\\n\\n'
    'This projection is derived by `agentsctl sync`; edit canonical `AGENTS.md`, '
    '`rules/`, `skills/`, or `commands/`, never this output. The operator\'s newe'
    'st request has precedence. Provider hooks are delivery mechanisms, not polic'
    'y owners.\\n\\n## Rule `architecture/engineering-core`\\n\\n# Engineering co'
    're\\n\\nFor every implementation:\\n\\n1. Research repository owners, depend'
    'encies, and canonical documentation.\\n2. Remove scope without a current req'
    'uirement or consumer (YAGNI).\\n3. Elect one writable authority; every other'
    ' copy is a generated projection\\n   (SSOT).\\n4. Apply SOLID only to a resp'
    'onsibility or dependency boundary under change.\\n5. Implement through the o'
    'wner and simplify without weakening behavior.\\n6. Remove duplication and go'
    'd components; recheck YAGNI, SSOT, SOLID.\\n7. Exercise runtime behavior, ru'
    'n every applicable native gate, and complete\\n   the approved landing cycle'
    ' before changing phase.\\n\\nAt a cross-boundary failure, prove the producer'
    ' contract and output. Fix its\\nowner when invalid or the receiver when it c'
    'onforms. Never alter a correct\\nadjacent owner for an invalid consumer; sym'
    'ptom workarounds are defects.\\n\\nHardcodes, normalized failure, failover, '
    'retry, fallback, compatibility,\\npartial execution, keyring, and unevidence'
    'd success are defects. Typed owners\\nkeep defaults. The first exception esc'
    'apes its CLI with traceback and cause.\\n\\nGit, runtime, build, and tests a'
    're baseline. Auxiliary tracking is a capability.\\nAuxiliary capabilities ap'
    'ply only when authorized and selected; installation\\nnever selects. Do not '
    'load, probe, or gate dormant capabilities. Invalid\\nselected authorization,'
    ' configuration, readiness, or result fails without\\nfallback. Require only '
    'non-derivable values.\\n\\nAn external token validation without its token is'
    ' not executed and is recorded\\nas `NOT EXECUTED`, never green; it does not '
    'block offline gates, landing, or\\npost-merge proof. Direct invocation selec'
    'ts it: the token becomes required and\\nany failure escapes without skip, ca'
    'tch, fallback, or normalization.\\n\\nCompose with `generalized ownership` ('
    'rule file),\\n`strict execution` (rule file),\\n`runtime evidence` (rule fil'
    'e),\\n`storage isolation` (rule file),\\n`security closure` (rule file).\\n\\n'
    '## Rule `coordination/operator-precedence`\\n\\n# Newest operator instructio'
    'n wins; adjust artifacts to it\\n\\nAuthority order: operator request > decl'
    'ared orchestration contract > canonical\\ntracker > ADRs > skills > docs, an'
    'd newest supersedes oldest. On conflict,\\nadjust the lower or older artifac'
    't to match; never override the operator to\\nsatisfy stale guidance.\\n\\nWh'
    'ile orchestration and tracker runtimes are suspended, do not invoke them.\\n'
    'Create no substitute tracker or ledger, preserve implementation evidence onl'
    'y\\nin separately authorized Git/PR/CI, and leave phase closure open.\\n\\nE'
    'xact operator authorization naming targets, disposition, recovery, and\\nval'
    'idation survives interruption, divergence, and red gates; re-preflight and\\n'
    'continue. Ask only when the effect expands beyond it or two evidenced curren'
    't\\nintentions conflict. State alone proves no intention, actor, or process.'
    '\\n\\n## Rule `ethics/professional-integrity`\\n\\n# Professional integrity '
    'is absolute\\n\\nNever lie, fabricate evidence, hide a blocker, bypass a gat'
    'e, or patch a symptom\\nonly to make a check pass. Fix the generalized root '
    'cause with full context and\\nreport exact command, working directory, exit '
    'code and decisive output.\\n\\n## Rule `runtime/strict-execution`\\n\\n# Str'
    'ict execution is universal and non-optional\\n\\nEvery project and projected'
    ' agent applies all of these policies together:\\n\\n- `fail loud` (rule file'
    ');\\n- `no fallback` (rule file);\\n- `preflight before effects` (rule file)'
    ';\\n- `required environment` (rule file);\\n- `atomic effects` (rule file);\\n'
    '- `causal subprocess propagation` (rule file);\\n- `no keyring` (rule file);'
    '\\n- `zero residue` (rule file).\\n\\nThe policies are cumulative. A project'
    ' rule may make them narrower or reject\\nmore inputs; it cannot relax, catch'
    ', normalize, skip, defer, or route around any\\nof them. Existing opposing b'
    'ehavior is a blocking violation to exterminate at\\nits owner, never grandfa'
    'thered compatibility.\\n\\nResolve gate applicability before invocation. A d'
    'ormant external-token gate is\\nnot executed; selecting or invoking it appli'
    'es every policy above.\\n\\n## Capability indexes\\n\\nSkills: caveman, cont'
    'ext-canary, fix-forward-collaboration, governance-audit, operator-correction'
    '-learning, plan-focus-recovery, sprint-closure, strategic-compact, verificat'
    'ion-loop\\nCommands: add-language-rules, database-migration, feature-develop'
    'ment, ghi-list, pr-list, ralph-loop, security-triage, synthesize-governance\\n'
    '"}}',
>>>>>>> dup-261007
)
json.dump(response, sys.stdout, ensure_ascii=False, separators=(",", ":"))
sys.stdout.write("\n")
