# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flext_grpc/protos/flext.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "flext_grpc/protos/flext.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1d\x66lext_grpc/protos/flext.proto\x12\rflext.grpc.v1"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t"E\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tserver_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t" \n\rHealthRequest\x12\x0f\n\x07service\x18\x01 \x01(\t"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9f\x01\n\x10\x46lextGrpcService\x12?\n\x04\x45\x63ho\x12\x1a.flext.grpc.v1.EchoRequest\x1a\x1b.flext.grpc.v1.EchoResponse\x12J\n\x0bHealthCheck\x12\x1c.flext.grpc.v1.HealthRequest\x1a\x1d.flext.grpc.v1.HealthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "flext_grpc.protos.flext_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ECHOREQUEST"]._serialized_start = 48
    _globals["_ECHOREQUEST"]._serialized_end = 78
    _globals["_ECHORESPONSE"]._serialized_start = 80
    _globals["_ECHORESPONSE"]._serialized_end = 149
    _globals["_HEALTHREQUEST"]._serialized_start = 151
    _globals["_HEALTHREQUEST"]._serialized_end = 183
    _globals["_HEALTHRESPONSE"]._serialized_start = 185
    _globals["_HEALTHRESPONSE"]._serialized_end = 234
    _globals["_FLEXTGRPCSERVICE"]._serialized_start = 237
    _globals["_FLEXTGRPCSERVICE"]._serialized_end = 396
# @@protoc_insertion_point(module_scope)
