# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from flext_grpc.protos import flext_pb2 as flext__grpc_dot_protos_dot_flext__pb2

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in flext_grpc/protos/flext_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FlextGrpcServiceStub:
    """mro-wkii.17.26 (codex): this schema is the sole source for Python gRPC modules."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
            "/flext.grpc.v1.FlextGrpcService/Echo",
            request_serializer=flext__grpc_dot_protos_dot_flext__pb2.EchoRequest.SerializeToString,
            response_deserializer=flext__grpc_dot_protos_dot_flext__pb2.EchoResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/flext.grpc.v1.FlextGrpcService/HealthCheck",
            request_serializer=flext__grpc_dot_protos_dot_flext__pb2.HealthRequest.SerializeToString,
            response_deserializer=flext__grpc_dot_protos_dot_flext__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class FlextGrpcServiceServicer:
    """mro-wkii.17.26 (codex): this schema is the sole source for Python gRPC modules."""

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FlextGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Echo": grpc.unary_unary_rpc_method_handler(
            servicer.Echo,
            request_deserializer=flext__grpc_dot_protos_dot_flext__pb2.EchoRequest.FromString,
            response_serializer=flext__grpc_dot_protos_dot_flext__pb2.EchoResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=flext__grpc_dot_protos_dot_flext__pb2.HealthRequest.FromString,
            response_serializer=flext__grpc_dot_protos_dot_flext__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "flext.grpc.v1.FlextGrpcService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "flext.grpc.v1.FlextGrpcService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class FlextGrpcService:
    """mro-wkii.17.26 (codex): this schema is the sole source for Python gRPC modules."""

    @staticmethod
    def Echo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flext.grpc.v1.FlextGrpcService/Echo",
            flext__grpc_dot_protos_dot_flext__pb2.EchoRequest.SerializeToString,
            flext__grpc_dot_protos_dot_flext__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flext.grpc.v1.FlextGrpcService/HealthCheck",
            flext__grpc_dot_protos_dot_flext__pb2.HealthRequest.SerializeToString,
            flext__grpc_dot_protos_dot_flext__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
