from .test_helpers import (
    assert_client_from_result as assert_client_from_result,
    assert_client_from_setup as assert_client_from_setup,
    assert_server_from_result as assert_server_from_result,
    assert_server_from_setup as assert_server_from_setup,
    assert_service_from_setup as assert_service_from_setup,
)

EXPECTED_DATA_COUNT: int

class TestCompleteGrpcWorkflow:
    def test_enterprise_grpc_setup_workflow(self) -> None: ...
    def test_streaming_workflow(self) -> None: ...
    def test_error_handling_workflow(self) -> None: ...
    def test_multi_service_workflow(self) -> None: ...
    def test_configuration_driven_workflow(self) -> None: ...
    def test_concurrent_clients_workflow(self) -> None: ...
    def test_full_library_integration(self) -> None: ...
    def test_performance_workflow(self) -> None: ...
