from collections.abc import Mapping

from flext_grpc import FlextGrpcClient, FlextGrpcServer

def assert_server_from_setup(
    setup_result: Mapping[str, object], key: str = "server"
) -> FlextGrpcServer: ...
def assert_client_from_setup(
    setup_result: Mapping[str, object], key: str = "client"
) -> FlextGrpcClient: ...
def assert_service_from_setup(
    setup_result: Mapping[str, object], key: str = "service"
) -> FlextGrpcService: ...
def assert_dict_from_result(result_data: object) -> dict[str, object]: ...
def assert_client_from_result(result_data: object) -> FlextGrpcClient: ...
def assert_server_from_result(result_data: object) -> FlextGrpcServer: ...
