# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

from typing import NoReturn

import grpc
from flx_grpc import flx_pb2 as flx__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_VERSION = grpc.__version__
GRPC_GENERATED_VERSION = "1.60.0"  # Default minimum version
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in flx_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FlxServiceStub:
    """Main FLX service definition"""
    def __init__(self, channel: object):
        """Constructor.

        Args:
            channel: A grpc.Channel.

        """
        self.GetSystemStats = channel.unary_unary(
            "/flx.FlxService/GetSystemStats",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=flx__pb2.SystemStats.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/flx.FlxService/HealthCheck",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=flx__pb2.HealthStatus.FromString,
            _registered_method=True,
        )
        self.GetSystemInfo = channel.unary_unary(
            "/flx.FlxService/GetSystemInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=flx__pb2.SystemInfo.FromString,
            _registered_method=True,
        )
        self.ListPipelines = channel.unary_unary(
            "/flx.FlxService/ListPipelines",
            request_serializer=flx__pb2.ListPipelinesRequest.SerializeToString,
            response_deserializer=flx__pb2.ListPipelinesResponse.FromString,
            _registered_method=True,
        )
        self.GetPipeline = channel.unary_unary(
            "/flx.FlxService/GetPipeline",
            request_serializer=flx__pb2.GetPipelineRequest.SerializeToString,
            response_deserializer=flx__pb2.Pipeline.FromString,
            _registered_method=True,
        )
        self.CreatePipeline = channel.unary_unary(
            "/flx.FlxService/CreatePipeline",
            request_serializer=flx__pb2.CreatePipelineRequest.SerializeToString,
            response_deserializer=flx__pb2.Pipeline.FromString,
            _registered_method=True,
        )
        self.UpdatePipeline = channel.unary_unary(
            "/flx.FlxService/UpdatePipeline",
            request_serializer=flx__pb2.UpdatePipelineRequest.SerializeToString,
            response_deserializer=flx__pb2.Pipeline.FromString,
            _registered_method=True,
        )
        self.DeletePipeline = channel.unary_unary(
            "/flx.FlxService/DeletePipeline",
            request_serializer=flx__pb2.DeletePipelineRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.RunPipeline = channel.unary_unary(
            "/flx.FlxService/RunPipeline",
            request_serializer=flx__pb2.RunPipelineRequest.SerializeToString,
            response_deserializer=flx__pb2.Execution.FromString,
            _registered_method=True,
        )
        self.GetExecution = channel.unary_unary(
            "/flx.FlxService/GetExecution",
            request_serializer=flx__pb2.GetExecutionRequest.SerializeToString,
            response_deserializer=flx__pb2.Execution.FromString,
            _registered_method=True,
        )
        self.ListExecutions = channel.unary_unary(
            "/flx.FlxService/ListExecutions",
            request_serializer=flx__pb2.ListExecutionsRequest.SerializeToString,
            response_deserializer=flx__pb2.ListExecutionsResponse.FromString,
            _registered_method=True,
        )
        self.CancelExecution = channel.unary_unary(
            "/flx.FlxService/CancelExecution",
            request_serializer=flx__pb2.CancelExecutionRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.StreamExecution = channel.unary_stream(
            "/flx.FlxService/StreamExecution",
            request_serializer=flx__pb2.StreamExecutionRequest.SerializeToString,
            response_deserializer=flx__pb2.ExecutionUpdate.FromString,
            _registered_method=True,
        )
        self.ListPlugins = channel.unary_unary(
            "/flx.FlxService/ListPlugins",
            request_serializer=flx__pb2.ListPluginsRequest.SerializeToString,
            response_deserializer=flx__pb2.ListPluginsResponse.FromString,
            _registered_method=True,
        )
        self.InstallPlugin = channel.unary_unary(
            "/flx.FlxService/InstallPlugin",
            request_serializer=flx__pb2.InstallPluginRequest.SerializeToString,
            response_deserializer=flx__pb2.Plugin.FromString,
            _registered_method=True,
        )
        self.UninstallPlugin = channel.unary_unary(
            "/flx.FlxService/UninstallPlugin",
            request_serializer=flx__pb2.UninstallPluginRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.GetPluginConfig = channel.unary_unary(
            "/flx.FlxService/GetPluginConfig",
            request_serializer=flx__pb2.GetPluginConfigRequest.SerializeToString,
            response_deserializer=flx__pb2.PluginConfig.FromString,
            _registered_method=True,
        )
        self.UpdatePluginConfig = channel.unary_unary(
            "/flx.FlxService/UpdatePluginConfig",
            request_serializer=flx__pb2.UpdatePluginConfigRequest.SerializeToString,
            response_deserializer=flx__pb2.PluginConfig.FromString,
            _registered_method=True,
        )
        self.GetState = channel.unary_unary(
            "/flx.FlxService/GetState",
            request_serializer=flx__pb2.GetStateRequest.SerializeToString,
            response_deserializer=flx__pb2.State.FromString,
            _registered_method=True,
        )
        self.SetState = channel.unary_unary(
            "/flx.FlxService/SetState",
            request_serializer=flx__pb2.SetStateRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.ClearState = channel.unary_unary(
            "/flx.FlxService/ClearState",
            request_serializer=flx__pb2.ClearStateRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.ListSchedules = channel.unary_unary(
            "/flx.FlxService/ListSchedules",
            request_serializer=flx__pb2.ListSchedulesRequest.SerializeToString,
            response_deserializer=flx__pb2.ListSchedulesResponse.FromString,
            _registered_method=True,
        )
        self.CreateSchedule = channel.unary_unary(
            "/flx.FlxService/CreateSchedule",
            request_serializer=flx__pb2.CreateScheduleRequest.SerializeToString,
            response_deserializer=flx__pb2.Schedule.FromString,
            _registered_method=True,
        )
        self.UpdateSchedule = channel.unary_unary(
            "/flx.FlxService/UpdateSchedule",
            request_serializer=flx__pb2.UpdateScheduleRequest.SerializeToString,
            response_deserializer=flx__pb2.Schedule.FromString,
            _registered_method=True,
        )
        self.DeleteSchedule = channel.unary_unary(
            "/flx.FlxService/DeleteSchedule",
            request_serializer=flx__pb2.DeleteScheduleRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.InitializeMeltanoProject = channel.unary_unary(
            "/flx.FlxService/InitializeMeltanoProject",
            request_serializer=flx__pb2.InitializeMeltanoProjectRequest.SerializeToString,
            response_deserializer=flx__pb2.MeltanoProject.FromString,
            _registered_method=True,
        )
        self.LoadMeltanoProject = channel.unary_unary(
            "/flx.FlxService/LoadMeltanoProject",
            request_serializer=flx__pb2.LoadMeltanoProjectRequest.SerializeToString,
            response_deserializer=flx__pb2.MeltanoProject.FromString,
            _registered_method=True,
        )
        self.RunMeltanoPipeline = channel.unary_unary(
            "/flx.FlxService/RunMeltanoPipeline",
            request_serializer=flx__pb2.RunMeltanoPipelineRequest.SerializeToString,
            response_deserializer=flx__pb2.MeltanoExecution.FromString,
            _registered_method=True,
        )
        self.GetMeltanoJobStatus = channel.unary_unary(
            "/flx.FlxService/GetMeltanoJobStatus",
            request_serializer=flx__pb2.GetMeltanoJobStatusRequest.SerializeToString,
            response_deserializer=flx__pb2.MeltanoJobStatus.FromString,
            _registered_method=True,
        )
        self.ListMeltanoJobs = channel.unary_unary(
            "/flx.FlxService/ListMeltanoJobs",
            request_serializer=flx__pb2.ListMeltanoJobsRequest.SerializeToString,
            response_deserializer=flx__pb2.ListMeltanoJobsResponse.FromString,
            _registered_method=True,
        )
        self.GetMeltanoState = channel.unary_unary(
            "/flx.FlxService/GetMeltanoState",
            request_serializer=flx__pb2.GetMeltanoStateRequest.SerializeToString,
            response_deserializer=flx__pb2.MeltanoState.FromString,
            _registered_method=True,
        )
        self.SetMeltanoState = channel.unary_unary(
            "/flx.FlxService/SetMeltanoState",
            request_serializer=flx__pb2.SetMeltanoStateRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.GetMeltanoJobStatistics = channel.unary_unary(
            "/flx.FlxService/GetMeltanoJobStatistics",
            request_serializer=flx__pb2.GetMeltanoJobStatisticsRequest.SerializeToString,
            response_deserializer=flx__pb2.MeltanoJobStatistics.FromString,
            _registered_method=True,
        )
        self.CleanupStaleMeltanoJobs = channel.unary_unary(
            "/flx.FlxService/CleanupStaleMeltanoJobs",
            request_serializer=flx__pb2.CleanupStaleMeltanoJobsRequest.SerializeToString,
            response_deserializer=flx__pb2.MeltanoJobCleanupResult.FromString,
            _registered_method=True,
        )
        self.RunMeltanoCommand = channel.unary_unary(
            "/flx.FlxService/RunMeltanoCommand",
            request_serializer=flx__pb2.RunMeltanoCommandRequest.SerializeToString,
            response_deserializer=flx__pb2.MeltanoCommandResult.FromString,
            _registered_method=True,
        )
        self.BatchOperations = channel.unary_unary(
            "/flx.FlxService/BatchOperations",
            request_serializer=flx__pb2.BatchOperationsRequest.SerializeToString,
            response_deserializer=flx__pb2.BatchOperationsResponse.FromString,
            _registered_method=True,
        )
        self.GetAdvancedMetrics = channel.unary_unary(
            "/flx.FlxService/GetAdvancedMetrics",
            request_serializer=flx__pb2.AdvancedMetricsRequest.SerializeToString,
            response_deserializer=flx__pb2.AdvancedMetricsResponse.FromString,
            _registered_method=True,
        )
        self.SystemMaintenance = channel.unary_unary(
            "/flx.FlxService/SystemMaintenance",
            request_serializer=flx__pb2.SystemMaintenanceRequest.SerializeToString,
            response_deserializer=flx__pb2.SystemMaintenanceResponse.FromString,
            _registered_method=True,
        )
        self.ManagePlugins = channel.unary_unary(
            "/flx.FlxService/ManagePlugins",
            request_serializer=flx__pb2.PluginManagementRequest.SerializeToString,
            response_deserializer=flx__pb2.PluginManagementResponse.FromString,
            _registered_method=True,
        )
        self.ManageConfiguration = channel.unary_unary(
            "/flx.FlxService/ManageConfiguration",
            request_serializer=flx__pb2.ConfigurationManagementRequest.SerializeToString,
            response_deserializer=flx__pb2.ConfigurationManagementResponse.FromString,
            _registered_method=True,
        )


class FlxServiceServicer:
    """Main FLX service definition"""
    def GetSystemStats(self, request: object, context: object):
        """System operations."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request: object, context: object) -> NoReturn:
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSystemInfo(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPipelines(self, request: object, context: object):
        """Pipeline operations."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPipeline(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatePipeline(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdatePipeline(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeletePipeline(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RunPipeline(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetExecution(self, request: object, context: object):
        """Execution operations."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListExecutions(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelExecution(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamExecution(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPlugins(self, request: object, context: object):
        """Plugin operations."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InstallPlugin(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UninstallPlugin(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPluginConfig(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdatePluginConfig(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetState(self, request: object, context: object):
        """State operations."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetState(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClearState(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSchedules(self, request: object, context: object):
        """Schedule operations."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateSchedule(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateSchedule(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteSchedule(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InitializeMeltanoProject(self, request: object, context: object):
        """Meltano orchestration operations."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LoadMeltanoProject(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RunMeltanoPipeline(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMeltanoJobStatus(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMeltanoJobs(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMeltanoState(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetMeltanoState(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMeltanoJobStatistics(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CleanupStaleMeltanoJobs(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RunMeltanoCommand(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchOperations(self, request: object, context: object):
        """Enterprise advanced operations (PHASE 1.3)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAdvancedMetrics(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SystemMaintenance(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ManagePlugins(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ManageConfiguration(self, request: object, context: object):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FlxServiceServicer_to_server(servicer: object, server: object) -> None:
    rpc_method_handlers = {
        "GetSystemStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemStats,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=flx__pb2.SystemStats.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=flx__pb2.HealthStatus.SerializeToString,
        ),
        "GetSystemInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=flx__pb2.SystemInfo.SerializeToString,
        ),
        "ListPipelines": grpc.unary_unary_rpc_method_handler(
            servicer.ListPipelines,
            request_deserializer=flx__pb2.ListPipelinesRequest.FromString,
            response_serializer=flx__pb2.ListPipelinesResponse.SerializeToString,
        ),
        "GetPipeline": grpc.unary_unary_rpc_method_handler(
            servicer.GetPipeline,
            request_deserializer=flx__pb2.GetPipelineRequest.FromString,
            response_serializer=flx__pb2.Pipeline.SerializeToString,
        ),
        "CreatePipeline": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePipeline,
            request_deserializer=flx__pb2.CreatePipelineRequest.FromString,
            response_serializer=flx__pb2.Pipeline.SerializeToString,
        ),
        "UpdatePipeline": grpc.unary_unary_rpc_method_handler(
            servicer.UpdatePipeline,
            request_deserializer=flx__pb2.UpdatePipelineRequest.FromString,
            response_serializer=flx__pb2.Pipeline.SerializeToString,
        ),
        "DeletePipeline": grpc.unary_unary_rpc_method_handler(
            servicer.DeletePipeline,
            request_deserializer=flx__pb2.DeletePipelineRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "RunPipeline": grpc.unary_unary_rpc_method_handler(
            servicer.RunPipeline,
            request_deserializer=flx__pb2.RunPipelineRequest.FromString,
            response_serializer=flx__pb2.Execution.SerializeToString,
        ),
        "GetExecution": grpc.unary_unary_rpc_method_handler(
            servicer.GetExecution,
            request_deserializer=flx__pb2.GetExecutionRequest.FromString,
            response_serializer=flx__pb2.Execution.SerializeToString,
        ),
        "ListExecutions": grpc.unary_unary_rpc_method_handler(
            servicer.ListExecutions,
            request_deserializer=flx__pb2.ListExecutionsRequest.FromString,
            response_serializer=flx__pb2.ListExecutionsResponse.SerializeToString,
        ),
        "CancelExecution": grpc.unary_unary_rpc_method_handler(
            servicer.CancelExecution,
            request_deserializer=flx__pb2.CancelExecutionRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "StreamExecution": grpc.unary_stream_rpc_method_handler(
            servicer.StreamExecution,
            request_deserializer=flx__pb2.StreamExecutionRequest.FromString,
            response_serializer=flx__pb2.ExecutionUpdate.SerializeToString,
        ),
        "ListPlugins": grpc.unary_unary_rpc_method_handler(
            servicer.ListPlugins,
            request_deserializer=flx__pb2.ListPluginsRequest.FromString,
            response_serializer=flx__pb2.ListPluginsResponse.SerializeToString,
        ),
        "InstallPlugin": grpc.unary_unary_rpc_method_handler(
            servicer.InstallPlugin,
            request_deserializer=flx__pb2.InstallPluginRequest.FromString,
            response_serializer=flx__pb2.Plugin.SerializeToString,
        ),
        "UninstallPlugin": grpc.unary_unary_rpc_method_handler(
            servicer.UninstallPlugin,
            request_deserializer=flx__pb2.UninstallPluginRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "GetPluginConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetPluginConfig,
            request_deserializer=flx__pb2.GetPluginConfigRequest.FromString,
            response_serializer=flx__pb2.PluginConfig.SerializeToString,
        ),
        "UpdatePluginConfig": grpc.unary_unary_rpc_method_handler(
            servicer.UpdatePluginConfig,
            request_deserializer=flx__pb2.UpdatePluginConfigRequest.FromString,
            response_serializer=flx__pb2.PluginConfig.SerializeToString,
        ),
        "GetState": grpc.unary_unary_rpc_method_handler(
            servicer.GetState,
            request_deserializer=flx__pb2.GetStateRequest.FromString,
            response_serializer=flx__pb2.State.SerializeToString,
        ),
        "SetState": grpc.unary_unary_rpc_method_handler(
            servicer.SetState,
            request_deserializer=flx__pb2.SetStateRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "ClearState": grpc.unary_unary_rpc_method_handler(
            servicer.ClearState,
            request_deserializer=flx__pb2.ClearStateRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "ListSchedules": grpc.unary_unary_rpc_method_handler(
            servicer.ListSchedules,
            request_deserializer=flx__pb2.ListSchedulesRequest.FromString,
            response_serializer=flx__pb2.ListSchedulesResponse.SerializeToString,
        ),
        "CreateSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSchedule,
            request_deserializer=flx__pb2.CreateScheduleRequest.FromString,
            response_serializer=flx__pb2.Schedule.SerializeToString,
        ),
        "UpdateSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateSchedule,
            request_deserializer=flx__pb2.UpdateScheduleRequest.FromString,
            response_serializer=flx__pb2.Schedule.SerializeToString,
        ),
        "DeleteSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSchedule,
            request_deserializer=flx__pb2.DeleteScheduleRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "InitializeMeltanoProject": grpc.unary_unary_rpc_method_handler(
            servicer.InitializeMeltanoProject,
            request_deserializer=flx__pb2.InitializeMeltanoProjectRequest.FromString,
            response_serializer=flx__pb2.MeltanoProject.SerializeToString,
        ),
        "LoadMeltanoProject": grpc.unary_unary_rpc_method_handler(
            servicer.LoadMeltanoProject,
            request_deserializer=flx__pb2.LoadMeltanoProjectRequest.FromString,
            response_serializer=flx__pb2.MeltanoProject.SerializeToString,
        ),
        "RunMeltanoPipeline": grpc.unary_unary_rpc_method_handler(
            servicer.RunMeltanoPipeline,
            request_deserializer=flx__pb2.RunMeltanoPipelineRequest.FromString,
            response_serializer=flx__pb2.MeltanoExecution.SerializeToString,
        ),
        "GetMeltanoJobStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetMeltanoJobStatus,
            request_deserializer=flx__pb2.GetMeltanoJobStatusRequest.FromString,
            response_serializer=flx__pb2.MeltanoJobStatus.SerializeToString,
        ),
        "ListMeltanoJobs": grpc.unary_unary_rpc_method_handler(
            servicer.ListMeltanoJobs,
            request_deserializer=flx__pb2.ListMeltanoJobsRequest.FromString,
            response_serializer=flx__pb2.ListMeltanoJobsResponse.SerializeToString,
        ),
        "GetMeltanoState": grpc.unary_unary_rpc_method_handler(
            servicer.GetMeltanoState,
            request_deserializer=flx__pb2.GetMeltanoStateRequest.FromString,
            response_serializer=flx__pb2.MeltanoState.SerializeToString,
        ),
        "SetMeltanoState": grpc.unary_unary_rpc_method_handler(
            servicer.SetMeltanoState,
            request_deserializer=flx__pb2.SetMeltanoStateRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "GetMeltanoJobStatistics": grpc.unary_unary_rpc_method_handler(
            servicer.GetMeltanoJobStatistics,
            request_deserializer=flx__pb2.GetMeltanoJobStatisticsRequest.FromString,
            response_serializer=flx__pb2.MeltanoJobStatistics.SerializeToString,
        ),
        "CleanupStaleMeltanoJobs": grpc.unary_unary_rpc_method_handler(
            servicer.CleanupStaleMeltanoJobs,
            request_deserializer=flx__pb2.CleanupStaleMeltanoJobsRequest.FromString,
            response_serializer=flx__pb2.MeltanoJobCleanupResult.SerializeToString,
        ),
        "RunMeltanoCommand": grpc.unary_unary_rpc_method_handler(
            servicer.RunMeltanoCommand,
            request_deserializer=flx__pb2.RunMeltanoCommandRequest.FromString,
            response_serializer=flx__pb2.MeltanoCommandResult.SerializeToString,
        ),
        "BatchOperations": grpc.unary_unary_rpc_method_handler(
            servicer.BatchOperations,
            request_deserializer=flx__pb2.BatchOperationsRequest.FromString,
            response_serializer=flx__pb2.BatchOperationsResponse.SerializeToString,
        ),
        "GetAdvancedMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.GetAdvancedMetrics,
            request_deserializer=flx__pb2.AdvancedMetricsRequest.FromString,
            response_serializer=flx__pb2.AdvancedMetricsResponse.SerializeToString,
        ),
        "SystemMaintenance": grpc.unary_unary_rpc_method_handler(
            servicer.SystemMaintenance,
            request_deserializer=flx__pb2.SystemMaintenanceRequest.FromString,
            response_serializer=flx__pb2.SystemMaintenanceResponse.SerializeToString,
        ),
        "ManagePlugins": grpc.unary_unary_rpc_method_handler(
            servicer.ManagePlugins,
            request_deserializer=flx__pb2.PluginManagementRequest.FromString,
            response_serializer=flx__pb2.PluginManagementResponse.SerializeToString,
        ),
        "ManageConfiguration": grpc.unary_unary_rpc_method_handler(
            servicer.ManageConfiguration,
            request_deserializer=flx__pb2.ConfigurationManagementRequest.FromString,
            response_serializer=flx__pb2.ConfigurationManagementResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "flx.FlxService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("flx.FlxService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class FlxService:
    """Main FLX service definition"""
    @staticmethod
    def GetSystemStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetSystemStats",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            flx__pb2.SystemStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/HealthCheck",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            flx__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSystemInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetSystemInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            flx__pb2.SystemInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPipelines(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/ListPipelines",
            flx__pb2.ListPipelinesRequest.SerializeToString,
            flx__pb2.ListPipelinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPipeline(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetPipeline",
            flx__pb2.GetPipelineRequest.SerializeToString,
            flx__pb2.Pipeline.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreatePipeline(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/CreatePipeline",
            flx__pb2.CreatePipelineRequest.SerializeToString,
            flx__pb2.Pipeline.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdatePipeline(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/UpdatePipeline",
            flx__pb2.UpdatePipelineRequest.SerializeToString,
            flx__pb2.Pipeline.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeletePipeline(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/DeletePipeline",
            flx__pb2.DeletePipelineRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RunPipeline(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/RunPipeline",
            flx__pb2.RunPipelineRequest.SerializeToString,
            flx__pb2.Execution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetExecution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetExecution",
            flx__pb2.GetExecutionRequest.SerializeToString,
            flx__pb2.Execution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListExecutions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/ListExecutions",
            flx__pb2.ListExecutionsRequest.SerializeToString,
            flx__pb2.ListExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelExecution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/CancelExecution",
            flx__pb2.CancelExecutionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamExecution(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/flx.FlxService/StreamExecution",
            flx__pb2.StreamExecutionRequest.SerializeToString,
            flx__pb2.ExecutionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPlugins(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/ListPlugins",
            flx__pb2.ListPluginsRequest.SerializeToString,
            flx__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def InstallPlugin(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/InstallPlugin",
            flx__pb2.InstallPluginRequest.SerializeToString,
            flx__pb2.Plugin.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UninstallPlugin(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/UninstallPlugin",
            flx__pb2.UninstallPluginRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPluginConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetPluginConfig",
            flx__pb2.GetPluginConfigRequest.SerializeToString,
            flx__pb2.PluginConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdatePluginConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/UpdatePluginConfig",
            flx__pb2.UpdatePluginConfigRequest.SerializeToString,
            flx__pb2.PluginConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetState",
            flx__pb2.GetStateRequest.SerializeToString,
            flx__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/SetState",
            flx__pb2.SetStateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ClearState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/ClearState",
            flx__pb2.ClearStateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListSchedules(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/ListSchedules",
            flx__pb2.ListSchedulesRequest.SerializeToString,
            flx__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/CreateSchedule",
            flx__pb2.CreateScheduleRequest.SerializeToString,
            flx__pb2.Schedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/UpdateSchedule",
            flx__pb2.UpdateScheduleRequest.SerializeToString,
            flx__pb2.Schedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/DeleteSchedule",
            flx__pb2.DeleteScheduleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def InitializeMeltanoProject(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/InitializeMeltanoProject",
            flx__pb2.InitializeMeltanoProjectRequest.SerializeToString,
            flx__pb2.MeltanoProject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LoadMeltanoProject(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/LoadMeltanoProject",
            flx__pb2.LoadMeltanoProjectRequest.SerializeToString,
            flx__pb2.MeltanoProject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RunMeltanoPipeline(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/RunMeltanoPipeline",
            flx__pb2.RunMeltanoPipelineRequest.SerializeToString,
            flx__pb2.MeltanoExecution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMeltanoJobStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetMeltanoJobStatus",
            flx__pb2.GetMeltanoJobStatusRequest.SerializeToString,
            flx__pb2.MeltanoJobStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMeltanoJobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/ListMeltanoJobs",
            flx__pb2.ListMeltanoJobsRequest.SerializeToString,
            flx__pb2.ListMeltanoJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMeltanoState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetMeltanoState",
            flx__pb2.GetMeltanoStateRequest.SerializeToString,
            flx__pb2.MeltanoState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetMeltanoState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/SetMeltanoState",
            flx__pb2.SetMeltanoStateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMeltanoJobStatistics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetMeltanoJobStatistics",
            flx__pb2.GetMeltanoJobStatisticsRequest.SerializeToString,
            flx__pb2.MeltanoJobStatistics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CleanupStaleMeltanoJobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/CleanupStaleMeltanoJobs",
            flx__pb2.CleanupStaleMeltanoJobsRequest.SerializeToString,
            flx__pb2.MeltanoJobCleanupResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RunMeltanoCommand(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/RunMeltanoCommand",
            flx__pb2.RunMeltanoCommandRequest.SerializeToString,
            flx__pb2.MeltanoCommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchOperations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/BatchOperations",
            flx__pb2.BatchOperationsRequest.SerializeToString,
            flx__pb2.BatchOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAdvancedMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/GetAdvancedMetrics",
            flx__pb2.AdvancedMetricsRequest.SerializeToString,
            flx__pb2.AdvancedMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SystemMaintenance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/SystemMaintenance",
            flx__pb2.SystemMaintenanceRequest.SerializeToString,
            flx__pb2.SystemMaintenanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ManagePlugins(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/ManagePlugins",
            flx__pb2.PluginManagementRequest.SerializeToString,
            flx__pb2.PluginManagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ManageConfiguration(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/flx.FlxService/ManageConfiguration",
            flx__pb2.ConfigurationManagementRequest.SerializeToString,
            flx__pb2.ConfigurationManagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
