from flext_core import FlextEntity, FlextResult

from flext_grpc.constants import (
    FLEXT_GRPC_MAX_PORT as FLEXT_GRPC_MAX_PORT,
    FLEXT_GRPC_MIN_PORT as FLEXT_GRPC_MIN_PORT,
)
from flext_grpc.typings import (
    TGrpcChannelState as TGrpcChannelState,
    TGrpcServerState as TGrpcServerState,
    TGrpcStreamType as TGrpcStreamType,
    TGrpcTarget as TGrpcTarget,
)

class FlextGrpcEntity(FlextEntity):
    @property
    def entity_type(self) -> str: ...

class FlextGrpcChannel(FlextGrpcEntity):
    target: TGrpcTarget
    state: TGrpcChannelState
    options: dict[str, object]
    def validate_business_rules(self) -> FlextResult[None]: ...
    def is_ready(self) -> bool: ...
    def connect(self) -> FlextResult[FlextGrpcChannel]: ...
    def mark_ready(self) -> FlextResult[FlextGrpcChannel]: ...
    def disconnect(self) -> FlextResult[FlextGrpcChannel]: ...

class FlextGrpcServer(FlextGrpcEntity):
    host: str
    port: int
    state: TGrpcServerState
    max_workers: int
    services: list[object]
    def validate_business_rules(self) -> FlextResult[None]: ...
    @property
    def address(self) -> str: ...
    @property
    def is_running(self) -> bool: ...
    def start(self) -> FlextResult[FlextGrpcServer]: ...
    def mark_running(self) -> FlextResult[FlextGrpcServer]: ...
    def stop(self) -> FlextResult[FlextGrpcServer]: ...
    def mark_stopped(self) -> FlextResult[FlextGrpcServer]: ...
    def add_service(
        self, service: FlextGrpcService
    ) -> FlextResult[FlextGrpcServer]: ...

class FlextGrpcService(FlextGrpcEntity):
    name: str
    methods: list[str]
    def validate_business_rules(self) -> FlextResult[None]: ...
    def has_method(self, method_name: str) -> bool: ...
    def add_method(self, method_name: str) -> FlextResult[FlextGrpcService]: ...

class FlextGrpcClient(FlextGrpcEntity):
    channel: FlextGrpcChannel | None
    options: dict[str, object]
    def validate_business_rules(self) -> FlextResult[None]: ...
    @property
    def is_connected(self) -> bool: ...
    @property
    def target(self) -> str | None: ...
    def connect_to(self, target: str) -> FlextResult[FlextGrpcClient]: ...

class FlextGrpcStream(FlextGrpcEntity):
    method_name: str
    stream_type: TGrpcStreamType
    def validate_business_rules(self) -> FlextResult[None]: ...
    @property
    def is_streaming(self) -> bool: ...
    @property
    def is_server_streaming(self) -> bool: ...
    @property
    def is_client_streaming(self) -> bool: ...
    @property
    def is_bidirectional(self) -> bool: ...

class FlextGrpcEntityFactory:
    @classmethod
    def create_server(
        cls,
        host: str = "localhost",
        port: int = 50051,
        max_workers: int = 10,
        **options: object,
    ) -> FlextResult[FlextGrpcServer]: ...
    @classmethod
    def create_client(
        cls, target: str, **options: object
    ) -> FlextResult[FlextGrpcClient]: ...
    @classmethod
    def create_channel(
        cls, target: str, **options: object
    ) -> FlextResult[FlextGrpcChannel]: ...
    @classmethod
    def create_service(
        cls, name: str, methods: list[str] | None = None, **options: object
    ) -> FlextResult[FlextGrpcService]: ...
    @classmethod
    def create_stream(
        cls, method_name: str, stream_type: str = "unary", **options: object
    ) -> FlextResult[FlextGrpcStream]: ...
