def example_1_basic_entities() -> None: ...
def example_2_configuration() -> None: ...
def example_3_operations() -> None: ...
def example_4_validation() -> None: ...
def example_5_state_transitions() -> None: ...
def main() -> None: ...
