from _typeshed import Incomplete

from flext_grpc import (
    FlextGrpcClient,
    FlextGrpcConfig,
    FlextGrpcServer,
    FlextGrpcService,
)

class GrpcServerManager:
    operations: Incomplete
    servers: dict[str, FlextGrpcServer]
    server_configs: dict[str, FlextGrpcConfig]
    def __init__(self) -> None: ...
    def create_server_pool(
        self, base_port: int = 8000, count: int = 3
    ) -> list[FlextGrpcServer]: ...
    def start_all_servers(self) -> dict[str, bool]: ...
    def stop_all_servers(self) -> dict[str, bool]: ...
    def get_server_status(self) -> dict[str, dict[str, str]]: ...

class GrpcClientPool:
    operations: Incomplete
    clients: dict[str, FlextGrpcClient]
    connection_status: dict[str, bool]
    def __init__(self) -> None: ...
    def create_clients_for_servers(
        self, servers: list[FlextGrpcServer]
    ) -> list[FlextGrpcClient]: ...
    def connect_all_clients(self) -> dict[str, bool]: ...
    def broadcast_call(
        self, method_name: str, data: object = None
    ) -> dict[str, object]: ...

class ServiceRegistry:
    services: dict[str, FlextGrpcService]
    service_servers: dict[str, str]
    def __init__(self) -> None: ...
    def register_service(self, service: FlextGrpcService, server_id: str) -> bool: ...
    def discover_services(self) -> dict[str, dict[str, object]]: ...
    def find_service_by_method(self, method_name: str) -> list[dict[str, str]]: ...

def example_1_server_pool() -> None: ...
def example_2_client_pool() -> None: ...
def example_3_service_registry() -> None: ...
def example_4_streaming() -> None: ...
def example_5_error_handling() -> None: ...
def main() -> None: ...
