from typing import Any

from _typeshed import Incomplete
from flext_core import FlextResult

logger: Incomplete

def validate_user_input(username: str, email: str) -> FlextResult[dict[str, str]]: ...
def create_server_config(port: int, workers: int) -> FlextResult[Any]: ...
def simulate_connection_error() -> FlextResult[str]: ...
def simulate_timeout_error() -> FlextResult[str]: ...
def handle_generic_grpc_error() -> FlextResult[str]: ...
def comprehensive_error_handling_pipeline() -> FlextResult[str]: ...
def error_recovery_patterns() -> FlextResult[str]: ...
def demonstrate_error_context() -> None: ...
async def async_error_handling() -> FlextResult[str]: ...
def main() -> None: ...
